[tool.briefcase]
project_name = "Calculator"
bundle = "com.abirshandilya.calculator"
version = "0.0.1"
url = "https://abirshandilya.com/calculator"
license = "BSD license"
author = 'Abir Shandilya'
author_email = "abirshandilya@gmail.com"

[tool.briefcase.app.calculator]
formal_name = "Calculator"
description = "A basic calculator beeware application"
icon = "src/calculator/resources/calculator"
sources = ['src/calculator']
requires = []


[tool.briefcase.app.calculator.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.calculator.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.calculator.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.calculator.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.calculator.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
